name: Merge into main branch

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deno:
    uses: ./.github/workflows/deno.yml

  tag:
    uses: ./.github/workflows/tag.yml
    needs: deno
    permissions:
      contents: read
      packages: write

  docker:
    uses: ./.github/workflows/docker.yml
    needs: tag
    with:
      image: saltman0/cinephoria-graphql
      tag: ${{ needs.tag.outputs.package_version }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    permissions:
      contents: read
      packages: write
