name: Merge into main branch

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deno-lint-and-test:
    uses: ./.github/workflows/deno-lint-and-test.yml

  codeql:
    uses: ./.github/workflows/codeql.yml

  build-and-publish-docker-image:
    uses: ./.github/workflows/build-and-publish-docker-image.yml
    needs: deno-lint-and-test
    with:
      image: saltman0/cinephoria-graphql
      tag: latest
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    permissions:
      contents: read
      packages: write